# Generated by Django 5.1.9 on 2025-07-22 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empleados", "0001_initial"),
        ("productos", "0001_initial"),
        ("sucursales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("motivo", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empleados.empleado",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sucursales.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salida",
                "verbose_name_plural": "Salidas",
            },
        ),
    ]
