# Generated by Django 5.1.9 on 2025-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
            },
        ),
    ]
