# Generated by Django 5.1.9 on 2025-07-22 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="apellido",
            field=models.CharField(default="Sin especificar", max_length=100),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_ingreso",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empleado",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
