version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inventario_db
    restart: always
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: inventario_db
      POSTGRES_PASSWORD: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario_net

volumes:
  postgres_data:

networks:
  inventario_net:




