services:
  - type: web
    name: toyosaki-inventario-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn inventario.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    autoDeploy: false
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: toyosaki-inventario-db
    plan: free
